name: your_track
description: Your Track.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_modular: ^6.3.2
  http: ^1.1.0
  flutter_triple: ^3.0.0
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  firebase_messaging: ^14.6.8
  firebase_storage: ^11.2.7
  firebase_remote_config: ^4.2.6
  cloud_firestore: ^4.9.2
  google_fonts: ^6.1.0
  dartz: ^0.10.1
  flutter_svg: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl_utils: ^2.8.4
  flutter_mobx: ^2.1.0
  dropdown_button2: ^2.3.9
  percent_indicator: ^4.2.3
  intl_phone_number_input: ^0.7.3+1
  built_value: ^8.6.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/dark/
    - assets/illustration/
    - assets/images/
    - assets/images/2x/
    - assets/images/3x/
    

