// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaMJk6C1LLim_qsW2pKvq081An4aFZvq4',
    appId: '1:13566507697:web:d64be24167e033bdb5c090',
    messagingSenderId: '13566507697',
    projectId: 'your-track',
    authDomain: 'your-track.firebaseapp.com',
    storageBucket: 'your-track.appspot.com',
    measurementId: 'G-W1NQKFZ224',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2BBXCDA8rSpisQNwfY_5xDGSCeRDXZ7k',
    appId: '1:13566507697:android:637223ee053d77a9b5c090',
    messagingSenderId: '13566507697',
    projectId: 'your-track',
    storageBucket: 'your-track.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBptGzVeCY9RFjJHxnQnQHvaQGsFEcOqsE',
    appId: '1:13566507697:ios:616cbfccdd52f27cb5c090',
    messagingSenderId: '13566507697',
    projectId: 'your-track',
    storageBucket: 'your-track.appspot.com',
    iosBundleId: 'com.example.yourTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBptGzVeCY9RFjJHxnQnQHvaQGsFEcOqsE',
    appId: '1:13566507697:ios:2dc7573337fd0c0fb5c090',
    messagingSenderId: '13566507697',
    projectId: 'your-track',
    storageBucket: 'your-track.appspot.com',
    iosBundleId: 'com.example.yourTrack.RunnerTests',
  );
}
